### ISSUE TITLE
Rename BottomSheet to BottomSheetLayout

### ISSUE THREAD

**Issue by mattlogan** [Flipboard/bottomsheet#1]
The distinction between a `BottomSheet` and a `SheetView` is pretty confusing. The way that I understand it is that `BottomSheet` is a custom `ViewGroup` that wraps an entire screen's layout -- not just the layout of the actual bottom sheet. And a `SheetView` is just the view that comes up from the bottom. This is confusing because the `SheetView` is the actually the bottom sheet here -- not the `BottomSheet`.

Why don't you adopt the convention used with `DrawerLayout` and the navigation drawer? Seems like a perfect analogy. The `DrawerLayout` wraps the entire screen's layout, while the navigation drawer is just the second child of the `DrawerLayout`.

I'm proposing that you rename `BottomSheet` to `BottomSheetLayout`, and rename the `SheetView` (I know this isn't actually a class in the library, but it is what you're calling the actual bottom sheet view) to `BottomSheet`.

**Comment by emilsjolander** [comment]
Great feedback! I think we should definitely do this. Will try to get it in tonight.
