### ISSUE TITLE
Request: add more states, in between the current states

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Flipboard/bottomsheet#106]
Currently there are those states:
        HIDDEN,
        PREPARING,
        PEEKED,
        EXPANDED

I wish to make it a bit different:

 - HIDDEN
 - USER_SCROLL_HIDDEN_PEEKED (user still touches the bottom layout to scroll it, between the states of hidden and peeked)
 - AUTO_SCROLL_HIDDEN_TO_PEEKED  (library scrolls from hidden state  to peeked state )
 - AUTO_SCROLL_PEEKED_TO_HIDDEN  (library scrolls from peeked state to hidden state )
 - PEEKED
 - USER_SCROLL_PEEKED_EXPANDED (similar to above)
 - AUTO_SCROLL_PEEKED_TO_EXPANDED  (...)
 - AUTO_SCROLL_EXPANDED_TO_PEEKED  (...)
 - EXPANDED

Only way to achieve this all is by using getViewTransformer and check there the various values, but this isn't a nice thing to do...

**Comment by hzsweers** [comment]
Please fork the library and do it yourself if you want this, as mentioned in other issues we are not going to change the API just for your needs.
