### ISSUE TITLE
Behavior with CoordinatorLayout as child

### ISSUE THREAD

**Issue by pmq** [Flipboard/bottomsheet#108]
Hi guys, first of all, thank you for BottomSheet, it rocks !

We've recently migrated a few activities to CoordinatorLayouts and it turns out that there are a few quirks in combination with BottomSheet. The most visible is that using BottomSheetLayout as the parent for CoordinatorLayout results in having a status bar that looses its translucent and overlay behavior.

I have reproduced on a very simple app used to showcase CoordinatorLayout, written by Chris Banes. You can check out the https://github.com/pmq/cheesesquare/tree/master branch for the default behavior without BottomSheet, and the https://github.com/pmq/cheesesquare/tree/demo-bottomsheet-behavior branch for the same layout but with a top-level BottomSheetLayout added.

Some screenshots if you just want to make sense of all that text :)

First the original :
![screenshot-original](https://cloud.githubusercontent.com/assets/516479/12008084/8990c6ac-ac25-11e5-909b-9e5a5158676b.jpg)

And here's the modified version with BottomSheet :
![screenshot-with-bottomsheet](https://cloud.githubusercontent.com/assets/516479/12008094/f93071c4-ac25-11e5-94ae-7cd88ad33fc5.jpg)

All apologies if I'm missing something obvious.
Take care.

**Comment by markrietveld** [comment]
From doing a bit of research, I think it might be because `android:fitsSystemWindows="true"` is set on the `CoordinatorLayout` inside the `BottomSheetLayout` [here](https://github.com/pmq/cheesesquare/commit/744f4eda5826f6b04307b606888dcaab19b55d53#diff-6324f3358e6e468cd04ec16ed1f8a47cR30)

As far as I know, `BottomSheetLayout` doesn't interact with the status bar, at least not intentionally

**Comment by pmq** [comment]
Thanks Mark. I've tried this suggestion and some other combinations. In either case, there are visual side effects to the combination. I'll keep digging !

**Comment by pmq** [comment]
Finally had some time to understand the problem. I just needed to request fullscreen programmatically in the activity just like `CoordinatorLayout` does when top-level, and it just worked. Thanks for your time.

**Comment by markrietveld** [comment]
:+1:
