### ISSUE TITLE
Possible issue when showing sheet after a long press

### ISSUE THREAD

**Issue by mttvll** [Flipboard/bottomsheet#11]
Hello,

I'm using the bottom sheet to display secondary actions for the items of a list. The sheet is shown when an item is long pressed.

The problem is, after the long press has been registered on the child view, if I don't lift the finger and start move it around the sheet intercepts those movement events and starts moving down.

Could a possible solution be intercepting touch events from the sheet layout only starting from a DOWN event? 
```
public boolean onInterceptTouchEvent(MotionEvent ev) {
    return ev.getActionMasked() == MotionEvent.ACTION_DOWN && isSheetShowing();
}  
```

Thanks for the great library!

**Comment by hzsweers** [comment]
Thanks for the heads up! We'll look into it
