### ISSUE TITLE
How can I keep the bottom sheet the same size when orientation changed?

### ISSUE THREAD

**Issue by andypho** [Flipboard/bottomsheet#113]
So I want the bottom sheet to be remain the same size when the orientation of the phone changes from portrait to landscape. Instead of the sheet matching the parent when its at landscape.

**Comment by hzsweers** [comment]
Can you be more specific? What layout params are you using, does the view fill the whole window (and thus force scrolling). It's likely that you're using wrap_content, and the content just fills the whole height in landscape. If you want peeked to remain peeked, you should use match_parent.

**Comment by andypho** [comment]
![screen shot 2016-01-08 at 9 13 31 pm](https://cloud.githubusercontent.com/assets/8908067/12195632/b7ae094c-b64c-11e5-9b71-ff2af8ae4bbd.png)
Im using your sample code atm. So when the phone orientation is on landscape mode. i want it to pop up like that in the pic.

**Comment by hzsweers** [comment]
I'm confused, I thought you didn't want it to match parent. Now you do?
