### ISSUE TITLE
Layout is not recognizing .java

### ISSUE THREAD

**Issue by cristianhoyos66** [Flipboard/bottomsheet#118]
I have these files:
```
public class PruebaActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_prueba);
        System.out.println("Saludos desde la actividad.java");

    }

}

```
activity_prueba.xml 
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    tools:context=".activities.PruebaActivity" >

    <TextView
        android:id="@+id/text_id"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:capitalize="characters"
        android:text="hello_world"
        android:textColor="@android:color/holo_blue_dark"
        android:textColorHighlight="@android:color/primary_text_dark"
        android:layout_centerVertical="true"
        android:textSize="50dp"/>

</RelativeLayout>
```

And I'm doing this in MainActivity:
```
bottomSheetLayout.showWithSheetView(LayoutInflater.from(MainActivity.this)
    .inflate(R.layout.activity_prueba, bottomSheetLayout, false));
```
but when layout is inflated **PruebaActivity** is not doing anything, when it would show **Saludos desde la actividad.java** 

But when I do this: 

```
startActivity(new Intent(MainActivity.this, PruebaActivity.class));
```
**PruebaActivity** works showing "Saludos desde la actividad.java" on Android Monitor.

I dont know if there is an another way to call my layout and that it works like bottomsheet and recognize PruebaActivity, because when I call my layout  whit this 
```
bottomSheetLayout.showWithSheetView
```
PruebaActivity looks as if it does not run.

Thanks

**Comment by hzsweers** [comment]
Can you link an example project that exhibits this? It's kind of hard to wrap my head around what you're wanting to do

**Comment by cristianhoyos66** [comment]
yes, a project with an example is here:

https://github.com/cristianhoyos66/bottomsheetexample

and you can see that when I open my activity_prueba.xml with:
```
startActivity(new Intent(this, PruebaActivity.class));
```
"Hello world from file.java" is shown on android monitor, but when I open my activity_prueba.xml of this way:
```

**Comment by cristianhoyos66** [comment]
I was doing some tests and I was looking for documentation about this: 
```
LayoutInflater.from(this).inflate(R.layout.activity_prueba, bottomSheetLayout, false);

```
And I was falling with the concept, I'm really sorry about this issue, so I close it.

Thank you :)
