### ISSUE TITLE
OutOfMemoryError with Imagepicker

### ISSUE THREAD

**Issue by 278956952** [Flipboard/bottomsheet#119]
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 0 free bytes and 3GB until OOM
	at android.os.Parcel.obtain(Parcel.java:2421)
	at android.os.Binder.execTransact(Binder.java:437)

**Comment by hzsweers** [comment]
You need to provide more information and context.

**Comment by 278956952** [comment]
the max image is 25, i think when load the picture, ImagePicker doesn't compress them！

**Comment by hzsweers** [comment]
The image picker doesn't do image loading, it only gives you a Uri. The image loading implementation is totally up to the user. I would recommend using an established library such as Glide or Picasso rather than handling it yourself. This not a bottomsheet issue.
