### ISSUE TITLE
How to set size of the sheet "preview"

### ISSUE THREAD

**Issue by paulcanning** [Flipboard/bottomsheet#123]
I am opening the bottom sheet as an initial "preview" (small part of it opens form the bottom of the screen)

I cannot find any documentation anywhere on how to set the size of this initial preview.

How can I set it to be a specific height, or, better yet, can I set it to wrap to the height of specified items in the view layout, e.g. only show a text heading on the sheet for the preview, then show the rest of the sheet when expanded?

**Comment by hzsweers** [comment]
Please just continue in the original issue rather than opening a new one
