### ISSUE TITLE
ViewPage, RecyclerView and Scrolling

### ISSUE THREAD

**Issue by alistairbrightec** [Flipboard/bottomsheet#125]
I am using a BottomSheetFragment, which contains a ViewPager with a FragmentPagerAdapter set on it. Then each of those fragments has a recyclerview inside them.

The issue I am having is that when you scroll down on a list it works fine. But when you then try to scroll the list up it won't and the bottom sheet seems to get the touch and starts to close. I have tried setting setInterceptContentTouch() but that seems to have no affect.

Is this a bug (in my code or yours) or is it not intended functionality? Any help would be greatly appreciated.

**Comment by hzsweers** [comment]
I think this is a bug in your code, you need to handle nested scrolling behavior correctly in your view.
