### ISSUE TITLE
Disable peek state

### ISSUE THREAD

**Issue by silviahisham** [Flipboard/bottomsheet#126]
How can I disable the peek state? I'm using ```MenuSheetView``` inside a ```NestedScrollView``` and a ```CoordinatorLayout``` and it only has 2 times but it always appears first in peek state, and I can't scroll it up to reveal the whole menu.

**Comment by hzsweers** [comment]
It sounds like you're using wrap content for your scrollview, which isn't going to expand past the peek state since the number of items isn't enough to justify anything else. Wrap your scrollview in a frame layout and set match_parent for its layout params

**Comment by silviahisham** [comment]
Actually the ```NestedScrollView``` has ```match_parent``` for its layout params, I'm using it inside a ```ViewPager``` with the ```ToolBar``` set to ```scroll|enterAlways``` so when it's scrolled up and hidden, the bottomSheet appears in expanded state, if I scroll the page down to reveal the toolBar, then the bottomSheet appears in the peek state and I'm not able to expand it by scrolling

**Comment by hzsweers** [comment]
Er... Ok that's hard to picture. Do you have a sample you can point me to?
