### ISSUE TITLE
Bug: Fragment bottomSheet nested scrolling behaviour may be incorrect

### ISSUE THREAD

**Issue by behelit** [Flipboard/bottomsheet#128]
This occurs when using the fragment bottomsheet.
If using a Collapsing Toolbar Layout with a collapsible image, the toolbar does not expand correctly after swiping down from a collapsed state.

For example:
1. Show fragment bottom sheet

2. Swipe up to top (so that fragment now fills the screen)
![Image of fragment in full view](http://i67.tinypic.com/sdegqd.png)

3. Swipe UP again so that toolbar and image collapses
![Image of fragment with collapsed toolbar](http://i67.tinypic.com/10fugzs.png)

4. Swipe DOWN, toolbar and image should expand, but in the case they don't. The fragment simply slides down without expanding. I'm assuming this has something to do with the nested scrolling behaviour because if I swipe left before swiping down, it will expand. Also, if I swipe up, past the end of the view, then go downwards, it will expand correctly.
![Image of fragment after swiping down](http://i66.tinypic.com/2nw2ywp.png)

I've uploaded the demo project based on the sample source here:
[demo project link](https://www.dropbox.com/s/xdgkf7v2zbg6w2s/bottomsheet-master-collapsingtoolbardemo.rar?dl=0)

**Comment by behelit** [comment]
I have re-tested using the base source code and it is working correctly so it is most likely a bug with my code.

**Comment by hzsweers** [comment]
I'm not sure how much we can do here, putting a coordinator layout in a bottomsheet is kind of overkill, and I think you'll have to handle the touch handling yourself unless you can point to a specific bug in the library.

**Comment by behelit** [comment]
I wouldn't say overkill when almost all of Google's apps use this approach.
I will try the native method and see if I can track down the nesting issue.

**Comment by hzsweers** [comment]
What I mean is: coordinator layout wants to be the root view, but here it's a child view. The sheet itself is scrolling, then it's trying to handle scrolling on its child views, can totally see them not playing nice.

**Comment by behelit** [comment]
I was able to do this properly with the native method, using bottom sheet dialog fragments.
They have fixed most of the bugs so I'm not sure if anyone needs this library anymore.
