### ISSUE TITLE
Interaction with views in the background

### ISSUE THREAD

**Issue by aadithyb** [Flipboard/bottomsheet#130]
I have implemented the Flipboard bottom sheet in a app. This is implemented along with the google maps (Very similar to the bottom sheet in google maps; click on balloon -> bottom sheet comes up). 

So I have got the bottom sheet to show up when a balloon is clicked and the bottom sheet takes a very small  portion of the screen. I want to let the user interact with the map fragment even though the bottom sheet is being shown. From what I understand after going through the source code and a bit of google search is that it is not possible right now. Is that correct or am I missing something? It would be awesome if you could tell me what I have missed if I have or suggest a work around.

Thanks

**Comment by hzsweers** [comment]
It's not possible right now because we don't have a "footer" state that you're thinking of. PRs welcome, but currently not a need or priority for us. Consider using the design support library implementation if you want that, or make your "peeked" translation equal to the height of your desired "footer" view

**Comment by aadithyb** [comment]
I tried using the design support library implementation but I faced some issues having a horizontal recycler view in the bottomsheet. I thought I'll post a question here to see if I'm missing something.

Could you please elaborate a little more on " make your "peeked" translation equal to the height of your desired "footer" view" ? Does this potentially solve the problem? 

And thanks for the label.

**Comment by aadithyb** [comment]
UPDATE --

I tried what you said and I think I understand what you meant. My question now is if its possible to possible to put a horizontal recycler view and interact with it on peek? (Assuming I set the peek's height/translation to cover the recycler view?

**Comment by hzsweers** [comment]
peek height sets the height of the peek in its peeked state. For touching outside the sheet, you can control that behavior via `BottomSheetLayout#setInterceptContentTouch()`

**Comment by hzsweers** [comment]
As far as horizontal recyclerview in the bottom sheet, that's an implementation detail specific to your app if you're seeing it in both the design support version and ours.

**Comment by aadithyb** [comment]
Awesome! setInterceptContentTouch was what I wanted. Thank you so much!

**Comment by hzsweers** [comment]
:+1:
