### ISSUE TITLE
Scrolling Bug

### ISSUE THREAD

**Issue by meierjan** [Flipboard/bottomsheet#132]
I have a strange scrolling issue with the BottomSheetView. Having a `ViewPager` in the `BottomSheetView` and one of its ScrollViews (most likely `RecyclerViews`) is scrolled to the top, the others can just scroll down. Scrolling up results in closing of the `BottomSheetView`

**Comment by hzsweers** [comment]
Please include sample code, link to a sample project, and/or a video. This issue alone is just a statement of some behavior that's impossible to investigate without more information.

**Comment by meierjan** [comment]
I think I found the bug in `BottomSheetLayout#canScrollUp`. As far as I understand its just asking all child-views recursively if they can scroll up. If a `View` says 'false' `BottomSheetView#onTouchEvent` line 344 it closes he bottom sheet.

**Comment by meierjan** [comment]
Already reported @  #125

**Comment by meierjan** [comment]
Video:
https://www.youtube.com/watch?v=KOVM9U0yMUg
