### ISSUE TITLE
Sharing Image with IntentPickerSheet

### ISSUE THREAD

**Issue by CeJienAJPC** [Flipboard/bottomsheet#136]
When I try to share Image using the IntentPickerSheet on devices (with versions above 16 and below KITKAT).
_AndroidSystem_ is the only option displayed. Clicking the _AndroidSystem_ displays the default dialog with the list of Apps suitable to share the image (images are attached for reference). However, the IntentPickerSheet functions as desired when trying to share text. Is the IntentSheetPicker restricted only to sharing texts?

Not sure what's happening. Any clues?

1. IntentPickerSheet with AndroidSystem
![device-2016-04-27-195158](https://cloud.githubusercontent.com/assets/15603039/14855663/87794fea-0cb2-11e6-9ae9-204d052d964e.png)

2. Clicking AndroidSystem displays Default dialog for sharing
![device-2016-04-27-195309](https://cloud.githubusercontent.com/assets/15603039/14855664/877f1bdc-0cb2-11e6-9918-9be52b841aee.png)

**Comment by markrietveld** [comment]
Can you paste the exact data your code puts into the `Intent`?

Did you try the starting the Intent directly (without an `IntentPickerSheet`) or making a chooser dialog with `Intent.createChooser`? What happens when you do that?

**Comment by hzsweers** [comment]
Closing due to lack of info or response
