### ISSUE TITLE
Bottom sheet hides when orientation changes

### ISSUE THREAD

**Issue by JackRoberts1998** [Flipboard/bottomsheet#142]
Hi, just started using your library but when you change orientation the sheet hides

**Comment by hzsweers** [comment]
Yes, you need to manage view restoration like any other view. You can use the fragment implementation in the commons library if you want something that does it for free.

**Comment by JackRoberts1998** [comment]
How do you change to fragment ?

**Comment by hzsweers** [comment]
The sample app has an example
