### ISSUE TITLE
Bug: showWithSheetView overwrites the layout param "width"

### ISSUE THREAD

**Issue by RocketRider** [Flipboard/bottomsheet#143]
The method showWithSheetView overwrites the layout param "width" from WRAP_CONTENT to defaultSheetWidth on tablets. At the same time there will be some values set, like sheetStartX. This is all correct if I run this code only once. But now if I call this method again on the same layout the value of "width" stays on defaultSheetWidth and the needed calculations are not performed.
So it uses wrong values which leads to incorrect touch events.

The reason why I found this is because I want to inflate the layout only once and hide and show the bottom panel multiple times.

I guess a fix could look like this:
```
 if (params.width == FrameLayout.LayoutParams.WRAP_CONTENT) {

            // Center by default if they didn't specify anything
            if (params.gravity == -1) {
                params.gravity = Gravity.CENTER_HORIZONTAL;
            }

            params.width = defaultSheetWidth;
}
if (params.width != FrameLayout.LayoutParams.MATCH_PARENT){
            int horizontalSpacing = screenWidth - params.width;
            sheetStartX = horizontalSpacing / 2;
            sheetEndX = screenWidth - sheetStartX;
}

```
I did not test this. What happens at the moment when I use a layout with a exact width? Does this work, because I see no calculation for sheetStartX in this case?

**Comment by hzsweers** [comment]
This is intentional, bottom sheet is always either match_parent or a specific width on tablets to match the material specs. If you want custom handling, you'll have to fork currently
