### ISSUE TITLE
Adding Fragments inside bottomsheet will work?

### ISSUE THREAD

**Issue by LOG-TAG** [Flipboard/bottomsheet#146]
By using Android AppCompat v23.2's BottomSheet it’s not possible to get a TabLayout / ViewPager with RecyclerView fragments working with a BottomSheet? I added this setup to AppCompat v23.2's  BottomSheet  but the recyclerviews won’t scroll. Any ideas why? we should  avoid adding Fragments inside BottomSheetDialogFragment!!  I just want to know this will work on this Flipboard/bottomsheet?

Plz add this to  [Question] tag

**Comment by meierjan** [comment]
You can add Fragments into this and even a ViewPager works fine with this if you are using the most recent version with the fix i provided.

**Comment by LOG-TAG** [comment]
working fine
