### ISSUE TITLE
Dismiss button when the sheet is expanded.

### ISSUE THREAD

**Issue by evant** [Flipboard/bottomsheet#15]
According to the [material design guidlines](https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-content) the sheet should have a dismiss button in the title when it's expanded. However, most (all?) of google's implementation don't have this button. Not sure if it's worth implementing, just thought I'd bring it up.

**Comment by hzsweers** [comment]
Oops, somehow missed that this was here. Yeah we have yet to see it in any of google's implementations, and would rather just leave this to the user for now.
