### ISSUE TITLE
ListView with the bottomsheet doesnt work

### ISSUE THREAD

**Issue by kidokimo** [Flipboard/bottomsheet#151]
I have a list view inside a fragment. this list has an adapter which gets the data from parse.com. the list works perfect. but when i place this list inside the bottom sheet it doesn't work. I obtain the data successfully from parse.com but I think the problem is the adapter doesn't updated or update the view when it placed inside the bottom sheet. so what is the solution for this issue.

**Comment by hzsweers** [comment]
Can you provide a sample project? Can't really speculate what you're doing in your code from that alone. Screen record of the issue would help too.
