### ISSUE TITLE
Set Expand Transition Height (Expand only the height of the sheet view)

### ISSUE THREAD

**Issue by yogesmhrj** [Flipboard/bottomsheet#152]
I am using this library to show a bottom sheet info for any place on my app. Currently my sheet view layout has its height set as `wrap_content`, thus the sheet view doesn't need to overlap all of the background content view when expanded. But when I implement the sheet, upon expand, the sheet moves straight up to the top. Is there a way to handle the height up to which the sheet can expand?

**Comment by yogesmhrj** [comment]
![device-2016-08-01-110940](https://cloud.githubusercontent.com/assets/13461608/17284218/8dfb04be-57d8-11e6-9dca-70ac953808b3.png)
here is a preview of what happens when is expand the view with wrap content.

**Comment by yogesmhrj** [comment]
This issue was solved with the following code snippet. 
```
this.bottomSheetLayout.setOnSheetStateChangeListener(new BottomSheetLayout.OnSheetStateChangeListener() {
            @Override
            public void onSheetStateChanged(BottomSheetLayout.State state) {
                if(state == BottomSheetLayout.State.EXPANDED){
                    int height = view.getHeight();
                    //lets not make the sheet expand up to the top, but only upto the height
                    bottomSheetLayout.setPeekSheetTranslation(height);
                    bottomSheetLayout.peekSheet();
                }
                if(state == BottomSheetLayout.State.PEEKED){
                    Log.d(TAG, "onSheetStateChanged: peeked --> ");
                }
            }
        });
```

**Comment by jemshit** [comment]
this breaks peek height
