### ISSUE TITLE
Shared element ???

### ISSUE THREAD

**Issue by tuanth89** [Flipboard/bottomsheet#156]
Hi everyone ! Thank for great library
When click item show bottom sheet and view transition above, Flipboard use shared element like below ?

![687474703a2f2f692e696d6775722e636f6d2f3265335a686f552e676966](https://cloud.githubusercontent.com/assets/11812307/18059885/5cc7fa04-6e45-11e6-8c81-3701d5224586.gif)

If not, pls give a sample code Flipboard use this animation ? I want to use it in my project.
Thanks

**Comment by tuanth89** [comment]
@hzsweers : sorry, do you know ???

**Comment by markrietveld** [comment]
@tuanth89 I'm not going the share Flipboard app code here, but I can tell you a little bit. 

When the user taps the flip button, we call `showWithSheetView` with a custom `ViewTransformer`. In there we determine the animation progress by dividing `translation` by `peekedTranslation`. We then scale and translate the article to it's new position based on that progress, while at the same time animating the alpha of all the unrelated views to 0.

**Comment by tuanth89** [comment]
@markrietveld : thank for reply. could you send me a sample code like GIF above ??
I just learn Android six month.

**Comment by markrietveld** [comment]
No, that will be for you to build yourself.
