### ISSUE TITLE
MenuSheetView is missing in gradle

### ISSUE THREAD

**Issue by slpereira** [Flipboard/bottomsheet#18]
I am trying to use MenuSheetView in my app, but the class is not included in the project when gradle downaload the classes.

**Comment by hzsweers** [comment]
Yes, sorry it's not released yet. We updated the README but made a new release yet. Will do soon!

**Comment by demogorgorn** [comment]
Hello! And when does it will be released? Thanks for the answer!

**Comment by hzsweers** [comment]
Soon.

**Comment by schwiz** [comment]
@hzsweers does the upcoming release make changes to the IntentPickerSheet as well? Currently using the Filter as shown in the README is not working. Should I open a ticket or is this also currently expected?

**Comment by hzsweers** [comment]
No functional changes, so please do open an issue!

**Comment by schwiz** [comment]
@hzsweers thanks turned out to be a pilot error. I had code to fallback to the system intent chooser if a bottom sheet container wasn't attached to the activity and they look so similar I couldn't tell the difference.

**Comment by hzsweers** [comment]
I'm just going to take that as a compliment on our UI parity :wink:

Thanks for following up, glad it was resolve

**Comment by DrSchrumpfi** [comment]
+1

**Comment by hzsweers** [comment]
We were waiting on a pull request to be finished, but haven't heard anything in awhile from the requester so tomorrow I'm just going to merge it and fix it up myself, then release an update

**Comment by hzsweers** [comment]
Release now in 1.3, should be available on jCenter in the next few hours!
