### ISSUE TITLE
BottomSheet.showWithSheetView() doesn't dim content view

### ISSUE THREAD

**Issue by mattlogan** [Flipboard/bottomsheet#2]
[The material design spec for bottom sheets](http://www.google.com/design/spec/components/bottom-sheets.html) states:

> When a bottom sheet is displayed, it animates upwards from the bottom edge of the screen. The rest of the screen dims, giving focus to the bottom sheet.

This looks like this:

![components_bottomsheets3](https://cloud.githubusercontent.com/assets/4635072/8010760/3eebf334-0b70-11e5-92e2-03eaf8f040a0.png)

Right now, this library only dims the content view when the sheet is translating between the "peek" mode and the "expanded" mode. When the sheet is sitting at the bottom of the screen after `showWithSheetView()` is called, there is no content view dimming, even with `shouldDimContentView` set to true.

![screenshot_2015-06-05-10-49-24](https://cloud.githubusercontent.com/assets/4635072/8010802/c001c4b2-0b70-11e5-9b1f-18ab0f5821f0.png)

I understand that this library was initially created for the Flipboard app, but it would be nice to have the option to have the content view dim according to the spec.

**Comment by emilsjolander** [comment]
@mattlogan Yes this is an oversight. I already have an implementation where this way the content is dimmed can be customized. Expect that to be released later today!

**Comment by mattlogan** [comment]
Awesome. Nice work!

**Comment by afollestad** [comment]
+1

A dimmed background (using a semi-transparent view below the bottom sheet which fills the screen) and small elevation would be nice. Material Design is all about sheets of paper that slide over and under each other.

**Comment by emilsjolander** [comment]
@mattlogan Changes have now been merged and default dimming behavior better matches that in material design.
