### ISSUE TITLE
App crashes when calling BottomSheet twice

### ISSUE THREAD

**Issue by demogorgorn** [Flipboard/bottomsheet#20]
App crashes when calling BottomSheet twice. So is it possible to prevent such behaviour?

**Comment by hzsweers** [comment]
We need more info. If you're trying to open the sheet when it's already showing, we purposely throw an [IllegalStateException](https://github.com/Flipboard/bottomsheet/blob/master/bottomsheet/src/main/java/com/flipboard/bottomsheet/BottomSheetLayout.java#L522-522).

**Comment by davideas** [comment]
Happened to me as well.
Cause is if BottomSheet is already visible an IllegalStateException is thrown.

**Comment by hzsweers** [comment]
@davideas this is expected behavior.

**Comment by davideas** [comment]
Indeed, user should check if sheet is already visible before trying to open it.
