### ISSUE TITLE
Feature Request : Peek the BottomSheet without Blocking UI interactions

### ISSUE THREAD

**Issue by shahimclt** [Flipboard/bottomsheet#22]
I am trying to implement bottomsheet over a mapView. I peek the bottomsheet when the user clicks on markers on the map. But the user should be able to:
1. either expand the bottom sheet to view the details (now possible) 
OR 
2. continue interacting with the map (i.e. content view) without dismissing the bottomsheet

P.S I would gladly like to help if anyone can guide me a little.

**Comment by schwiz** [comment]
I re-wrote the IntentPickerSheet due to this.

**Comment by hzsweers** [comment]
We're working on it, sorry for not leaving a heads up.
