### ISSUE TITLE
Util visibility

### ISSUE THREAD

**Issue by schwiz** [Flipboard/bottomsheet#24]
Util in commons has some strange visibility. It is a public class but all of its methods are package private. Perhaps it should be package private as well or set the methods to to public if you intend other devs to use the methods to make sheets. 

Also the Constructor should be made private and throw an AssertException.

**Comment by hzsweers** [comment]
Oops, yeah that was supposed to be package level only as well. Kind of
threw stuff in there without really putting any thought into it. Generally
don't want other developers to rely on those methods though, maaaaybe
exposing the outline provider implementation. We're probably going to do a
bugfix release pretty soon for the two other existing issues, so I'll clean
it up before then.
