### ISSUE TITLE
为什么在小米1s上分享面板是空白的？ 系统是android4.1的，小米4上（系统为android4.4）ok的。

### ISSUE THREAD

**Issue by hxingever** [Flipboard/bottomsheet#29]

**Comment by rengwuxian** [comment]
Translation for my colleagues:
Why is the sharing panel entirely blank on Xiaomi Mi 1s? OS version: Android 4.1. It works fine on Xiaomi Mi 4 (Andorid 4.4).

同学们以后还是请尽量打英文……

**Comment by st028** [comment]
Thanks for the heads up! We'll look into it.

**Comment by st028** [comment]
After some digging, this seems like an issue with grid layouts on android versions <= 4.2. 

This bug has somewhat of a false positive in that if you don't have any apps that can share (usually the case with newly provisioned emulators), the sharing panel will be empty.

**Comment by st028** [comment]
This is the same issue as what we're seeing in #31, so I'm going to close this issue. We'll track this bug there.
