### ISSUE TITLE
Grid items for IntentPickerSheetView not shown when running on Android <= 4.2

### ISSUE THREAD

**Issue by mknudsen** [Flipboard/bottomsheet#31]
The grid items for the IntentPickerSheetView are not visible (and as far as I can tell part not part of the view hierarchy) when running on older android devices.

I am using bottomsheet version 1.3.0. I tried this on android 4.2 and 4.1 devices. I have an example project here https://github.com/mknudsen/bottomsheet-android-4.2-issue

**Comment by hzsweers** [comment]
Yup we just noticed this yesterday as well, working on it!

**Comment by st028** [comment]
An update: it looks like this issue is caused by setting the number of columns in onLayout on both MenuSheetView and IntentPickerSheetView. Will open a PR on this soon.

**Comment by mknudsen** [comment]
Is it my messy backporting of the fix or does this error still persist in Android 4.2? 4.1 looks fine though.

**Comment by st028** [comment]
Good catch. We need to check if the current sdk is JELLY_BEAN_MR1.

**Comment by pelegb** [comment]
When will you release this?
