### ISSUE TITLE
FragmentSheet

### ISSUE THREAD

**Issue by SamThompson** [Flipboard/bottomsheet#46]
This commons component should take a fragment and show it in the bottomsheet.

**Comment by evant** [comment]
As a workaround, I'm giving the bottom sheet a view that's just a FrameLayout with an id. And then adding a fragment to the fragment manager with that id.

**Comment by markrietveld** [comment]
That sounds right. That should be the canonical solution

**Comment by evant** [comment]
Actually, can you reopen this? Fragment support has turned out to be nontrivial. In addition to knowing how to add the fragment correctly for the bottom sheet to measure correctly, you need to save and restore state across rotation in order to not have the app crash when trying to re-attach the fragment to a now missing id.

**Comment by markrietveld** [comment]
Sure

**Comment by efung** [comment]
Also, handling the Back button press. I tried adding a fragment to the Bottom Sheet, and pressing Back did not cause the bottom sheet to be dismissed, but caused the Activity to get finished.

**Comment by Zeliret** [comment]
Thats how I do it in my code for now:

```java
private void doShowBottomSheet(final Fragment fragment) {
        View view = new FrameLayout(getContext());
        view.setId(R.id.bottom_sheet_fragment);
        view.setBackgroundResource(R.color.background);

        BottomSheetLayout layout = getBase().getBottomSheetLayout();
        layout.setOnSheetStateChangeListener(state -> {
            if (state == BottomSheetLayout.State.PREPARING) {
                FragmentManager fm = getActivity().getSupportFragmentManager();
                fm.beginTransaction()
                  .replace(view.getId(), fragment)
                  .commit();
            }

            switch (state) {
                case PEEKED:
                    sheetShown = true;
                    sheetExpanded = false;
                    break;
                case EXPANDED:
                    sheetShown = true;
                    sheetExpanded = true;
                    break;
                default:
                    sheetShown = false;
                    sheetExpanded = false;
                    break;
            }
        });

        layout.showWithSheetView(view, null, bottomSheetLayout -> {
            FragmentManager fm = getActivity().getSupportFragmentManager();
            fm.beginTransaction()
              .remove(fragment)
              .commit();
        });
}
```

But there is an annoying problem that at the first attempt the fragment is not showing. Only second time and so on. :(
I think the first time it can't measure the view. If I swipe to expand the sheet it shows.

I'm sorry for my bad english. I did my best to explain the situation :)

**Comment by evant** [comment]
That's probably because `fm.commit()` is not immediate. Try doing `fm.executePendingTransactions()` right after adding the fragment.

**Comment by Zeliret** [comment]
@evant Well, if I use `fm.executePendingTransactions()`, the fm throws an exception that a container view is not found.

**Comment by evant** [comment]
Oh right you have to do it after the view is attached to the window. If I get some time, I'll write up a proper way to do this. We are doing it in our app but I'm not particularly happy with the solution.

**Comment by evant** [comment]
Ok, created a pull request with a solution that's based on DialogFragment https://github.com/Flipboard/bottomsheet/pull/79

**Comment by Zeliret** [comment]
@evant I think you have done a great job! I look forward when the PR will be accepted.

**Comment by hzsweers** [comment]
Done via #79
