### ISSUE TITLE
Change Peek height / Disable peek?

### ISSUE THREAD

**Issue by SteveEdson** [Flipboard/bottomsheet#47]
I'm using the `MenuSheetView`, however I only have about 5 items that I need to show. I don't like how the 3 items are visible when peaked, but you have to drag it up to see the other 2 options.

Is it / could it be possible to adjust the peek height, either so that a certain number of menu items are visible, or so that the `peek` state is disabled, and the menu goes from collapsed, straight to expanded.

Thanks.

**Comment by hzsweers** [comment]
Support for setting custom peek height has been added in master and will be available in the next release

**Comment by SteveEdson** [comment]
Awesome, thanks.

**Comment by SteveEdson** [comment]
This is working well in 1.4, thanks.
