### ISSUE TITLE
Center PeekSheet

### ISSUE THREAD

**Issue by pixelbendr** [Flipboard/bottomsheet#55]
Hello, How can I easily centre the peek sheet on button click.

**Comment by hzsweers** [comment]
I'm not sure what you mean by center, could you elaborate?

**Comment by pixelbendr** [comment]
Ok, you know the bottom sheet pops up  3 quarters below the screen. I want to centre the x position. so calculation like bottom sheet child view / 2 so it animates to the centre of the screen initially.

**Comment by hzsweers** [comment]
You can set a custom peek sheet translation: https://github.com/Flipboard/bottomsheet/blob/master/bottomsheet/src/main/java/com/flipboard/bottomsheet/BottomSheetLayout.java#L539-L546

That's all height related, so I'm not sure what you mean with the x position. Does that solve your problem?

**Comment by pixelbendr** [comment]
Yes looks like what I was look for. Will test now and let you know. Thanks for this.

**Comment by hzsweers** [comment]
No problem, feel free to reopen the issue if it doesn't resolve it for you.
