### ISSUE TITLE
Swap Sheets

### ISSUE THREAD

**Issue by SteveEdson** [Flipboard/bottomsheet#56]
I realise this may be more of a design issue on my part, but would it be possible to add the ability to swap sheets without having to dismiss and re-open?

I have a menu sheet with a list of options, one option is to upload an image, which is picked via the new image sheet, therefore it would be nice to show (and optionally animate via a slide) the new sheet immediately.

Thanks.

**Comment by hzsweers** [comment]
That's a fair point, and we agreed today that it would be nice to gracefully handle this within `BottomSheetLayout` as well. Going to think on how best to approach it, but definitely something we want to do.

**Comment by SteveEdson** [comment]
Glad to hear it. Currently it is a bit messy, its not possible to dismiss the sheet and immediately show a new one, I'm having to dismiss it, and wait for the state to change in the listener before I can show the new one.

**Comment by markrietveld** [comment]
@SteveEdson I think in most cases when showWithSheet is called when another sheet is showing, the intention will be to replace the existing one, so I'm proposing to make that the default in #59
