### ISSUE TITLE
Change content of bottom sheet?

### ISSUE THREAD

**Issue by paulcanning** [Flipboard/bottomsheet#61]
I am using a layout XML file for my bottom sheet, with a single textview in it.

How do I go about changing the value of the textview?

I tried the following, but it didn't work:

TextView title = (TextView) bottomSheet.findViewById(R.id.sheetTitle);
title.setText(marker.getTitle());

**Comment by hzsweers** [comment]
This isn't really a bottom sheet issue. You should be creating the sheet view separately and then showing it. Since you've created it separately, you have all the access you need to the view there.

**Comment by paulcanning** [comment]
Well I tried doing that, I showed my code that failed. I can't find
anything in the docs or library to figure it out.

I'm just after a pointer on how to access the elements in the view so I can
change text etc before showing the bottom sheet.

**Comment by hzsweers** [comment]
Your code doesn't really paint a full picture. Can you paste or link me exactly how you're setting the view on the sheet?

**Comment by paulcanning** [comment]
Exactly how it is shown in the readme:

BottomSheetLayout bottomSheet = (BottomSheetLayout) findViewById(R.id.bottomsheet);

Then the following is fired when tapping a button:

bottomSheet.showWithSheetView(LayoutInflater.from(context).inflate(R.layout.my_sheet_layout, bottomSheet, false));

So in the onclick handler, I tried the code I posted originally to try and set the text of the text view. 

I was confident it would work, but it doesn't and I don't get any errors either.

**Comment by hzsweers** [comment]
If you pull out `LayoutInflater.from(context).inflate(R.layout.my_sheet_layout, bottomSheet, false)` separately, can you retrieve the views from that?

Like so:

```java
View myView = LayoutInflater.from(context).inflate(R.layout.my_sheet_layout, bottomSheet, false);
TextView title = (TextView) myView.findViewById(R.id.sheetTitle);
title.setText(marker.getTitle());
```

**Comment by paulcanning** [comment]
That works, thanks!
