### ISSUE TITLE
When I run the demo, picker and menu can not be full screen,

### ISSUE THREAD

**Issue by qq137712630** [Flipboard/bottomsheet#67]
When I run the demo, picker and menu can not be full screen,
![s50918-114153](https://cloud.githubusercontent.com/assets/8408444/9951598/fd5192c0-5dfa-11e5-9f44-642986fb6385.jpg)

HiTestActivity:

  protected BottomSheetLayout bottomSheetLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hi_test);
        bottomSheetLayout = (BottomSheetLayout) findViewById(R.id.bottomsheet);
        bottomSheetLayout.setPeekOnDismiss(true);
        findViewById(R.id.btn_hi_test).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                showView();
            }

        });
    }

    private void showView() {
        HiTestView mHiTestView = new HiTestView(this);
        bottomSheetLayout.showWithSheetView(mHiTestView);
    }

HiTestView 

    public HiTestView(Context context) {
        super(context);
        inflate(getContext(), R.layout.hi_sheet_view, this);
    }

hi_sheet_view

	<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
		android:orientation="vertical"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:background="@android:color/white">

		<TextView
			android:id="@+id/title"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_marginEnd="24dp"
			android:layout_marginLeft="24dp"
			android:layout_marginRight="24dp"
			android:layout_marginStart="24dp"
			android:gravity="center_vertical"
			android:text="hi test"
			android:textColor="@color/text_gray"
			android:textSize="16sp" />
	</LinearLayout>

**Comment by markrietveld** [comment]
Hi @qq137712630. The default layout params for sheets have `WRAP_CONTENT` for the height, which makes it so the sheet can only be opened as much as it can fill. If you want the sheet to always be openable all the way, you can set these layout params on the sheet before calling `showWithSheetView`:
```java
mHiTestView.setLayoutParams(new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
```

**Comment by qq137712630** [comment]
Thank you for your great help
