### ISSUE TITLE
Update the wiki resources for IntentPickerSheetView

### ISSUE THREAD

**Issue by ViksaaSkool** [Flipboard/bottomsheet#68]
In the wiki on the main page and in [this blog post] (http://bit.ly/1KqKrFk) you have presented the following code regarding the use of IntentPickerSheetView:

```java
IntentPickerSheetView intentPickerSheet = new IntentPickerSheetView(MainActivity.this, shareIntent, "Share with...", new IntentPickerSheetView.OnIntentPickedListener() {
    @Override
    public void onIntentPicked(Intent intent) {
        bottomSheet.dismissSheet();
        startActivity(intent);
    }
});
```

With the latest update the `onIntentPicked` doesn't have `Intent` as parameter, instead it has `IntentPickerSheetView.ActivityInfo`. With that being said, the example should be modified in order to work properly. I have managed to do that in the following manner: 

```java
IntentPickerSheetView intentPickerSheetView = new IntentPickerSheetView(MainActivity.this, shareIntent, "Share via...", new IntentPickerSheetView.OnIntentPickedListener() {
            @Override
            public void onIntentPicked(IntentPickerSheetView.ActivityInfo activityInfo) {
                bottomSheet.dismissSheet();
                startActivity(activityInfo.getConcreteIntent(shareIntent));
            }
        });
```

**Comment by hzsweers** [comment]
Unfortunately blog posts will always eventually become out of date as a library progresses. The README and current wiki should be considered the accurate reflection of the current API state.
