### ISSUE TITLE
Is it possible to move the sheet so that it can cover maximum area

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [Flipboard/bottomsheet#7]
Hi , how can i increase the view which appears on clicking share so that it can cover maximum area till top . I want only 30-40 dp gap when it appears and when it is scrolled then it is fine.

So can i guide me how to achieve this?

Actually many of the apps have used this feature and this library is very close it. Like airbnb . This app has listview which comes from bottom and user has the ability to scroll it as much as he can. It just leaves a space from top(so that the view behind it can be seen). The rest of the featue i.e full view on scroll issame as you have done

**Comment by hzsweers** [comment]
So I think I'm following, but I don't quite understand what you mean by this line:

> I want only 30-40 dp gap when it appears and when it is scrolled then it is fine.

Could you elaborate? Also maybe showing some screenshots from airbnb to illustrate what you're talking about would be helpful.
