### ISSUE TITLE
Sheet intercepting touch events from RecyclerView.

### ISSUE THREAD

**Issue by evant** [Flipboard/bottomsheet#71]
I'm using a RecyclerView inside the bottom sheet in several places in my app. I've noticed that sometimes the sheet intercepts the touch event to scroll the RecyclerView back to the top and moves the sheet instead. If I start the scroll in the other direction first it works correctly.

**Comment by hzsweers** [comment]
That's strange. I wrote a pretty extensive new view component using
recyclerview recently and didn't see anything like this. Could you give a
snippet of code that reproduces this, or is it just random?

Other potential areas of trouble are if your view is wrap_content or has
text input with adjustSize set on your activity.

**Comment by hzsweers** [comment]
Going to close this for now, feel free revisit if you're able to nail down the issue. For an example of a recyclerview in the sheet, check out the comments view for any item in the flipboard app

**Comment by meierjan** [comment]
I am facing this too. Anything I should keep my eyes open for that could cause this issue?
