### ISSUE TITLE
onClickListener on BottomSheet is not working

### ISSUE THREAD

**Issue by david145** [Flipboard/bottomsheet#73]
Hey,
I attached a onClickListener on the BottomSheet to let it disappear, but nothing happens, when I click/tap on it. 

As a comparison, the onTouchListener on it works great, but I can't drag the BottomSheet using it.

Also setting a onClickListener on the containing View is not a solution, because it's not filling the whole screen.

Here a code snippet:

        bottomSheet = (BottomSheetLayout) findViewById(R.id.bottomsheet);
        bottomSheet.setShouldDimContentView(false);
        gifView = LayoutInflater.from(this).inflate(R.layout.gif_animation_view, bottomSheet, false);

        bottomSheet.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                bottomSheet.dismissSheet();
                Log.i(INFO_LOG_99, "dismissing sheet");
            }
        });

I can put a invisible view filling the whole BottomSheet and adding a onClickListener on it as a workaround, but I'm just curios why it's not working directly on the BottomSheet.

**Comment by david145** [comment]
I can put a invisible view filling the whole BottomSheet and adding a onClickListener on it as a workaround, but I'm just curios why it's not working directly on the BottomSheet.

**Comment by hzsweers** [comment]
Can you provide more info? I'm not sure why you'd want to set an onClickListener on the sheet itself, it's meant to be a container with views in it. That could easily have unpredictable behavior by interfering with touches/dragging/etc. A sample I could try that exhibits this would help a lot.

**Comment by david145** [comment]
![screenshot_2015-10-08-11-21-28](https://cloud.githubusercontent.com/assets/11370593/10354749/ee3f21da-6dae-11e5-96be-487475ce54d4.png)

I'm just showing a single gif in the bottom sheet and want to dismiss it, as soon as a user taps on it.

**Comment by david145** [comment]
I solved it now like this:

        bottomSheet.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                if (event.getAction() == MotionEvent.ACTION_UP) {
                    bottomSheet.dismissSheet();
                }

                return false;
            }
        });

Works great for me and I'm still able to drag the Botttomsheet. I think the event is already handled somewhere in your onTouch/onDrag implementation and so the onClick doesn't receive anything.
