### ISSUE TITLE
What license this comes with??

### ISSUE THREAD

**Issue by tuhin10** [Flipboard/bottomsheet#74]
Can i use this library in my project?

**Comment by hzsweers** [comment]
License is right here: https://github.com/Flipboard/bottomsheet/blob/master/LICENSE

**Comment by AndroidDeveloperLB** [comment]
@hzsweers So it's about the same as apache ?
What's the difference between the two?

**Comment by hzsweers** [comment]
You should ask a lawyer.

**Comment by AndroidDeveloperLB** [comment]
@hzsweers Why being rude? English isn't my main language, so that's why I ask this.

**Comment by hzsweers** [comment]
I am not being rude. I'm being honest. I didn't design the license, flipboard's lawyers did. I am not in a position to explain their differences to you.

**Comment by AndroidDeveloperLB** [comment]
I don't think a lawyer should be used for using github's repos (or any repos). It should be easy to use for all.
