### ISSUE TITLE
bottomSheet background color?

### ISSUE THREAD

**Issue by TheLoyalCruel** [Flipboard/bottomsheet#76]
how to change background color of the sheet?
and... is there any way to change the menu items typeface (font) when inflating a menu?
thanks...

**Comment by markrietveld** [comment]
The view being displayed as a sheet is a regular view, so if you're writing your own sheet, you can set any background on it you want. The menu sheet has a built-in background, and there is currently no API on it to configure the background. The same is true of the typeface. We're open to pull requests that add configurability for those

**Comment by Winghin2517** [comment]
You can set the color from the xml you are inflating from.

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Upload a picture"
        android:layout_margin="16dp"
        />
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Option 1"
        android:layout_marginBottom="16dp"
        android:layout_marginLeft="16dp"
        />
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Option 2"
        android:layout_marginBottom="16dp"
        android:layout_marginLeft="16dp"
        />
    
</LinearLayout>

**Comment by Morteza-Rastgoo** [comment]
Any change in the progress?
