### ISSUE TITLE
BottomSheet appears to go behind the statusBar

### ISSUE THREAD

**Issue by Winghin2517** [Flipboard/bottomsheet#77]
Hello

I have the following code that I inflate for my bottom sheet:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/white">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Upload a picture"
        android:layout_margin="16dp"
        />
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Option 1"
        android:layout_marginBottom="16dp"
        android:layout_marginLeft="16dp"
        />
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Option 2"
        android:layout_marginBottom="16dp"
        android:layout_marginLeft="16dp"
        />
</LinearLayout>

It inflates fine - but the problem is that if you drag the bottomsheet to the top of the screen, some of it hides behind the statusBar.

Before I drag it to the top (peekSheet):

![borttomsheet](https://cloud.githubusercontent.com/assets/7094734/10588234/69d7a8fe-76a5-11e5-8ff7-7caca98ea9b3.PNG)

After dragging it to the top - you can see that the "Upload a picture" text is hidden somewhat :

![bottomsheetexpanded](https://cloud.githubusercontent.com/assets/7094734/10588240/6d9a5dc4-76a5-11e5-85dd-ee200e6fa803.PNG)

**Comment by Winghin2517** [comment]
Sorry - I figured it out guys.

I had the following code in my layout file:

<com.flipboard.bottomsheet.BottomSheetLayout
    android:id="@+id/bottomsheet"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.design.widget.CoordinatorLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        >

Because I have said android:fitsSystemWindows="true", it actually stretches the bottomsheet to behind the statusbar. Removing that line corrects the display.

**Comment by markrietveld** [comment]
Great. I'm happy you figured it out

**Comment by Naveen9453** [comment]
Hi.. I am facing problem with bottom sheet.
In my case when i am opening MenuItems as bottom sheet then it works fine.
but when i want to open my custom layout (linearLayout or RelativeLayout) it create problem for me..
Can any one help me..
can anyone send the code with axml file and code to open BottomSheet in activity. with brief explanation.
Thanks in advanced.

**Comment by Winghin2517** [comment]
The reason why this happens is because your xml contain
android:fitsSystemWindows="true"

Remove this line from your xml and it should work.

**Comment by Naveen9453** [comment]
My Problem is when i am writing the code 

CoordinatorLayout coordinatorLayout = (CoordinatorLayout) FindViewById(Resource.Id.rootBottomSheet);
			View bottomSheet = coordinatorLayout.FindViewById(Resource.Id.bottomSheetLayout);
			**BottomSheetBehavior** behavior = **BottomSheetBehavior**.from (bottomSheet);

at BottomSheetBehavior it is showing error.that it does not exist in the current context.

**Comment by hzsweers** [comment]
@Naveen9453 you are looking for the design support library's bottomsheet, not this one.
