### ISSUE TITLE
When the bottomsheet listview is short, you can drag the sheet misplaced.

### ISSUE THREAD

**Issue by molikto** [Flipboard/bottomsheet#80]
![1 pic](https://cloud.githubusercontent.com/assets/1373829/10990959/bd046fd4-8493-11e5-918a-b73dd2b88d26.jpg)

**Comment by hzsweers** [comment]
I've seen this before as well

**Comment by molikto** [comment]
https://www.youtube.com/watch?v=HjNkzglZTPE&feature=youtu.be 

This is how i repro it.

**Comment by mccutcb1** [comment]
In [**BottomSheetLayout.java** :: **expandSheet()**](https://github.com/Flipboard/bottomsheet/blob/master/bottomsheet/src/main/java/com/flipboard/bottomsheet/BottomSheetLayout.java#L498) function:

```Java
ObjectAnimator anim = ObjectAnimator.ofFloat(this, SHEET_TRANSLATION, getHeight());
```
Should be replaced with:
```Java
ObjectAnimator anim = ObjectAnimator.ofFloat(this, SHEET_TRANSLATION, getMaxSheetTranslation());
```

This will prevent the sheet from filling the full height of the view and limit its height to the content *(if it is smaller)* when expandSheet() is called from anywhere in the code.
