### ISSUE TITLE
The sheet starts at wrong place if the content size changes dynamically 

### ISSUE THREAD

**Issue by molikto** [Flipboard/bottomsheet#81]
see the recording:

https://www.youtube.com/watch?v=py30LHdFwpM&feature=youtu.be

**Comment by pixelbendr** [comment]
@molikto Can I get the code for browsing photos and videos smoothly like you have done?

**Comment by hzsweers** [comment]
@molikto please try the latest master and see if that resolves the issue

**Comment by markrietveld** [comment]
Should be fixed in v1.5.0, which is available on JCenter now
