### ISSUE TITLE
Click X & Y are slightly off on phones

### ISSUE THREAD

**Issue by chanakin** [Flipboard/bottomsheet#87]
If you place views with OnClickListeners into the bottom sheet view, only the top part of the view registers clicks on phones.

I resolved this by copying down the source code and changing line 446 to calculate the offset and push it down further (for some reason 24dp seems to be the magic number):

```event.offsetLocation(isTablet ? getX() - sheetStartX : 0, sheetTranslation - getHeight() - (isTablet ? 0 : DesignUtils.convertDpToPixel(24)));```

in onTouchEvent(). Full method with changes:

     @Override
        public boolean onTouchEvent(@NonNull MotionEvent event) {
            if (!isSheetShowing()) {
                return false;
            }
            if (isAnimating()) {
                return false;
            } 
            if (!hasIntercepted) {
                return onInterceptTouchEvent(event);
            }

        ....
            } else {
                // If the user clicks outside of the bottom sheet area we should dismiss the bottom sheet.
                boolean touchOutsideBottomSheet = event.getY() < getHeight() - sheetTranslation || !isXInSheet(event.getX());
                if (event.getAction() == MotionEvent.ACTION_UP && touchOutsideBottomSheet && interceptContentTouch) {
                    dismissSheet();
                    return true;
                }

                /******* CHANGE MADE HERE *********/
                event.offsetLocation(isTablet ? getX() - sheetStartX : 0, sheetTranslation - getHeight() - (isTablet ? 0 : DesignUtils.convertDpToPixel(24)));
                getSheetView().dispatchTouchEvent(event);
            }

            return true;
        }

I should put in a pull request, but I'm not confident this is the appropriate way to address this. Ran this code on Sony Xperia Z3 Compact running 5.1.1 and a LG Optimus Exceed 2 running 4.4.2 and it resolved the touch point issue. On a Barnes & Noble Nook running 4.0.4 and a Nexus 7 running 5.1.1 work fine with the code as it is currently in the project.

**Comment by hzsweers** [comment]
24dp seems a little too magic-number-y. Could you post a screenshot or screenrecord of the behavior?

**Comment by chanakin** [comment]
Agreed, thus why I posted here as opposed to putting in a pull request--definitely a "Uh, hardcoded value seems weird here" moment.

I'll see about a screen recording. The screenshot likely won't help since you need to see that my finger is touching the view dead-on but the click isn't being registered.

**Comment by chanakin** [comment]
If you look at the screenshots below, with the touchpoints on the first card on the stars, only the first 1, with the touch point above the actual view, registered a click. All the others, despite actually touching the view, did not register a click.

![screenshot_2015-11-23-13-51-19](https://cloud.githubusercontent.com/assets/6220053/11351113/aab1ba40-91e9-11e5-8ae8-ab5bd5d5f15f.png)
![screenshot_2015-11-23-13-51-13](https://cloud.githubusercontent.com/assets/6220053/11351114/aacf7508-91e9-11e5-8a13-7af1dab35560.png)
![screenshot_2015-11-23-13-51-08](https://cloud.githubusercontent.com/assets/6220053/11351115/aad1fe36-91e9-11e5-8e88-803d517283fe.png)
![screenshot_2015-11-23-13-51-03](https://cloud.githubusercontent.com/assets/6220053/11351116/aadfa464-91e9-11e5-827a-d3a1f4da5c15.png)

**Comment by chanakin** [comment]
Would like to also note, despite my other issue being opened (which uses the same magic number), this issue is unrelated. I removed any padding from my sheet view and it had no effect on this issue.

**Comment by hzsweers** [comment]
I've been thinking on this, and I'm drawing a blank as far as what could be going on here. I can't find any references to those devices misreporting their events, and also can't repro this myself (though I'm limited to genymotion and a nexus 6P). If you breakpoint it, does the touch event report this too?

**Comment by chanakin** [comment]
To clarify, where would you like me to put a breakpoint and report back on the results? In the method that I modified?

**Comment by hzsweers** [comment]
right, breakpoint onTouch and see if the values match up if you turn on the pointer location developer option

**Comment by chanakin** [comment]
I'm not going to bother you with this any further as I've moved to use Google's BottomSheet APIs. Thanks for your help...although if you are going to continue maintaining this library it's definitely still an issue (ultimately that's why I moved to Google's implementation).

**Comment by hzsweers** [comment]
Sorry I was still waiting for your follow-up but never heard anything, that's why I closed it.

**Comment by chanakin** [comment]
No problem, I dropped the ball there. Sorry, in the middle of an all-out sprint to release, so I just didn't have time to sit and troubleshoot to figure out what was off. Even my workaround stopped being effective. I'll make a note on my calendar to take a look once I get this app out the door.

**Comment by hzsweers** [comment]
Sounds good, thanks!
