### ISSUE TITLE
Offset for bottom sheet view is off

### ISSUE THREAD

**Issue by chanakin** [Flipboard/bottomsheet#88]
My code:

XML for the bottom sheet view (note the fragment, but even extracting the view out of the fragment and into a plain view, this issue still persisted):

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        android:paddingBottom="24dp">

        <fragment
            android:id="@+id/review_fragment"
            android:name="MyViewFragment"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
    </LinearLayout>

The fragment's XML:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <ProgressBar
            android:id="@+id/loading"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:indeterminate="true" />

         <TextView
            android:id="@+id/empty_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:gravity="center"
            android:padding="16dp"
            android:paddingBottom="112dp"
            android:textSize="20sp"
            android:visibility="gone"
            tools:text="Blah blah blah empty text"
            tools:visibility="visible" />

        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
    </RelativeLayout>

If I don't include the ```android:paddingBottom="24dp"``` on my sheet view XML (or some other form, I tried a layout_margin on the fragment in that XML as well, either works), then the bottom sheet view gets cut off upon scrolling completely down in the list.

**Comment by hzsweers** [comment]
Could you include a screenshot of the behavior? We justed fixed something in master related to this and wondering if it might be the same issue you're seeing.

**Comment by chanakin** [comment]
This is the view above without the padding, scrolled all the way to the bottom of the recyclerview.

![screenshot_2015-11-23-13-48-19](https://cloud.githubusercontent.com/assets/6220053/11351101/8f381c64-91e9-11e5-98c1-9665580115cb.png)

**Comment by hzsweers** [comment]
Sorry about the delayed response. I'm not entirely sure what's going on here. Is there any chance you could put together a small sample project that I can run and play with on this? It's hard to tell just looking at the screenshot and those layout snippets
