### ISSUE TITLE
How do I retain sheet state on orientation change?

### ISSUE THREAD

**Issue by oligazar** [Flipboard/bottomsheet#90]
I'd like to retain sheet state is it peeked or expanded on orientation change. I've implement this with peek state. But I wonder how to deal with expandSheet() method. If I call it with showSheetWithView before it result will be just peek state. But call to expandSheet() without showSheetWithView() will lead to NullPointerException: Attempt to invoke virtual method 'void android.view.View.setLayerType(int, android.graphics.Paint)' on a null object reference. So how do I use expandSheet() properly?

**Comment by hzsweers** [comment]
The next release will support a BottomSheet fragment, which should achieve this effect.
