### ISSUE TITLE
How to make it work on top of activity's content, but still allow to click both?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Flipboard/bottomsheet#93]
On Google Maps, when you search for a place, a bottom-sheet appears, yet both it and the content above it are touchable.

How do I have this behavior?

**Comment by AndroidDeveloperLB** [comment]
OK, I've made a fork for this:
https://github.com/AndroidDeveloperLB/bottomsheet

And it works...

**Comment by AndroidDeveloperLB** [comment]
Wish I knew how to suggest to push the changes.

**Comment by hzsweers** [comment]
This is configurable via [setInterceptContentTouch](https://github.com/Flipboard/bottomsheet/blob/master/bottomsheet/src/main/java/com/flipboard/bottomsheet/BottomSheetLayout.java#L759)

**Comment by AndroidDeveloperLB** [comment]
@hzsweers Oops. Didn't notice that. Why is it named this way ? Why not something with the word "persistent" ?
Also, other issues:
1. dimming should be disabled when using this, using setShouldDimContentView .
2. it's impossible to import directly from Android Studio. Need to clone first.
3. Not sure though why I don't see shadows. Is it possible to add it to all Android versions?

**Comment by AndroidDeveloperLB** [comment]
I suggest to put a sample for the persistent bottom sheet, including to put a shadow.

Say, do you also know how to do it like on Google maps , where it has 3 steps of scrolling:
1. bottom sheet
2. almost full content+ large photo at the top
3. no photo at the top, being replaced by a toolbar 

?
Something like that:
![device-2015-12-08-000829](https://cloud.githubusercontent.com/assets/5357526/11641271/097c35d0-9d40-11e5-94c6-f9bef5f5ab9d.gif)

**Comment by hzsweers** [comment]
> Why is it named this way ? Why not something with the word "persistent" ?

Because that is the most accurate name. "Persistent" is ambiguous, as it could also mean the sheet is not dismissible at all. This name is exactly what behavior it controls. 

> dimming should be disabled when using this, using setShouldDimContentView .

Most users probably want that, but setters should only be atomic changes and not make perhaps unexpected changes to other states of the sheet. This is normal, and disabling dim is just as easy.

> it's impossible to import directly from Android Studio. Need to clone first.

Import what directly? This has been present since version 1.4. Make sure you're using jCenter()

> Not sure though why I don't see shadows. Is it possible to add it to all Android versions?

Shadows won't show up pre-5.0, and don't stand out much on 5.0+. The "light source" is effectively "above" the screen, so the shadows are most obvious beneath views. Since the sheet's edge is only at the top, the shadow (16dp) is barely visible. It's much more obvious on tablets where it's not full width my default.

> I suggest to put a sample for the persistent bottom sheet, including to put a shadow.

We're open to PRs, that would be a cool example to have. It won't be called a "persistent" sheet though :)

> Say, do you also know how to do it like on Google maps , where it has 3 steps of scrolling:

I do not off the top of my head. That UI's sheet has 4 states though. Collapsed - Peeked - Expanded. You would need to do some magic with View Transformer, and probably forfeit use of the collapsed bar at the bottom unless you want to fork and add a 4th state.

**Comment by AndroidDeveloperLB** [comment]
Well "persistent" is the term used by Google:
https://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-persistent-bottom-sheets
Or maybe I don't understand it well, and they mean it doesn't even scroll, working like a static snackbar ?

About dimming, ok.

About import, I meant import the project of course: open Android-Studio. click on VCS->checkout from version control->git , and then put : "https://github.com/Flipboard/bottomsheet.git" inside, and try to import this way.

About shadows, can you please consider adding it on pre-Lollipop ?

About the sample, ok.

About the Google-maps, that's right. This is what I've noticed. How do I work with the View-Transformer?

**Comment by hzsweers** [comment]
I'm pretty sure they mean that it's always partially visible. However, that's not what **setInterceptContentTouch** is controlling, hence why "persistent" is not the right name.

Importing the project works fine for me, you'll have to troubleshoot it yourself.

We use the framework's elevation settings for shadows, and that was not added until 5.0+. Unless Google magically backports elevation to pre-5.0, we will not be adding shadows to pre-lollipop.

ViewTransformer documentation can be found [here](https://github.com/Flipboard/bottomsheet/blob/master/bottomsheet/src/main/java/com/flipboard/bottomsheet/ViewTransformer.java), and an example can be found in the wiki [here](https://github.com/Flipboard/bottomsheet/wiki/Recipes#basicviewtransformer).

**Comment by AndroidDeveloperLB** [comment]
I mean: do they also mean it's still scrollable?

About importing, no, because Android-Studio can import other projects just fine, on 2 PCs I've tested (at home and at the office), and not this one. There is no setting I can change for this. I've even re-installed the IDE and all of the SDK components just to make sure it's not it.

About elevation, Google has a shadow (not one used by elevation, but still) for the toolbar and for CardView, so this one should also have it. Not only that, but it's shown on the guidelines.
I'm also pretty sure that all bottom sheets that Google is using have shadows even on pre-Lollipop.

About ViewTransformer , thank you . I'll check it out.

**Comment by hzsweers** [comment]
> do they also mean it's still scrollable?

Unrelated. I'm telling you that persistent just means it's always at least partially visible. 

Regarding android studio: like I said, you're on your own. You've provided no information as to what is going wrong other than that you just can't. That is unrelated to this project. Please seek help in a more appropriate place, such as stackoverflow.

Regarding the shadows: if it is so trivial, everyone would do it. There are plenty of other things in the material design guidelines that don't have platform support pre-lollipop, such as ripples and shared element transitions. Cards and actionbars (*not* toolbars) have custom implementations designed specifically for them, it's not a trivial job. We are not going to simply "backport" elevation.

**Comment by AndroidDeveloperLB** [comment]
So if it's always partially visible, I guess the back button won't close
them, but instead close the activity.

About Android Studio, it is related to the project, because you can't
import it in the normal way.
StackOverflow isn't for importing projects. It's not even a programming
question.

The solution about shadows is already described in Google's videos: they
use 9-patch images.
About ripples, this was also being talked about, and Google said it won't
be added because all of their attempts were not satisfying (bad
performance).
I'm not saying to backport elevation, but only for the shadow, in case the
bottom sheet is straight at the top.

**Comment by hzsweers** [comment]
You're welcome to make these custom 9 patches for yourself if you think it would be that simple. Alternatively you can make a sheet view that has a cardview at its root.

As for your IDE issues: Then maybe ask on the android developers group on G+. The project clones fine and we've accepted multiple PRs from other users with no complaints. I think it is a problem on your end. `you can't import it in the normal way` really isn't enough information for anyone to help you though. 

I'm locking this thread now, good luck.
