### ISSUE TITLE
Question: is it possible to set which view is the part of peeking

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Flipboard/bottomsheet#95]
...so that setPeekSheetTranslation won't be needed?

This way, if I change the peeking view's content, it will automatically have the height it's needed?

**Comment by AndroidDeveloperLB** [comment]
Also, is it possible to set that the expanded state would take the whole space that's available?

**Comment by hzsweers** [comment]
You can have the sheet be wrap_content. Please don't use the issue tracker just to ask quick questions, we have a gitter setup for that (see the README)

**Comment by AndroidDeveloperLB** [comment]
Setting the sheep to "wrap_content" won't allow to set the height of the sheet to match the one of the upper view. It will just use the default height of the sheet.
The readme (the main page of the repo) doesn't say anything about gitter setup. Only "API documentation" and "Recipes" .

**Comment by hzsweers** [comment]
Then this is a dupe of #66. It's planned but no time frame.

There's a button right at the top. <img width="301" alt="screen shot 2015-12-08 at 1 21 34 pm" src="https://cloud.githubusercontent.com/assets/1361086/11668918/a494e8dc-9dae-11e5-8e4e-fe123d413e56.png">

**Comment by AndroidDeveloperLB** [comment]
I didn't ask for a special view. I asked for how to make the bottom sheet to have the same size as a specific view, without the need to call "setPeekSheetTranslation". Is this really what they request there?

Also about the button, since I don't know what's "gitter", and there is no writing about it, I would have never though about clicking this. Even now it's not what I want, because I don't want to chat and spam all who's in there. I don't see there anything similar to threads. Only a single chat for all. I want to have an answer to a simple question, and as opposed to chat, I might not be near the PC when a new answer arrives. Here it's the best place to ask about issues, requests etc... It's the repo itself.

**Comment by hzsweers** [comment]
Ah. You can just as easily get the desired view's height and setPeekTranslation to use that height. It's a trivial thing to do, we are not going to build in special hookups to the API just for your specific use case. Going by your other issues, your ultimate goal here is to replicate the Google Maps UI. You are going to be better off forking the project and building it yourself, we are not going to do it for you.
