### ISSUE TITLE
Persistent onSheetStateChangeLister with custom views

### ISSUE THREAD

**Issue by teroaij** [Flipboard/bottomsheet#97]
I need to be able to monitor sheet state changes, while changing the content of the sheet. I previously did that using showWithSheetView, but as that clears the list of change listeners, my app logic is now broken.

How to achieve the same with the new API, being able to base logic on the sheet states?

**Comment by hzsweers** [comment]
showWithSheetView doesn't clear the listeners, dismiss does. Can you elaborate what you mean by "the new API"? 

If you're talking about showing a new sheet when one is already showing, there is an issue already open regarding this in #92. If that's the case, you'll need to manual set the listeners again for now until we have a better solution.

**Comment by teroaij** [comment]
OK, it was the same issue. At which point should I set the listeners, after a call to showWith..when the sheet is already showing? Since the asynch dismiss will clear away those?

**Comment by hzsweers** [comment]
You'll have to not use the asynch approach for now. I realize it's a regression so we'll get a fix at least out soon!

**Comment by MatFl** [comment]
@teroaij I currently use a workaround where I check if the sheet is showing, add a new DismissListener and then dismiss it. In the Listener I post a Runable in the hope, that the dismiss animation is already finished by then. The Runable then starts the new sheet and adds the new listeners. This works quite well.
Unfortunately I'm not allowed to post the here code for legal reasons of my company.
