### ISSUE TITLE
NPE when calling peekSheet() after dismissSheet()

### ISSUE THREAD

**Issue by steffandroid** [Flipboard/bottomsheet#98]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setLayerType(int, android.graphics.Paint)' on a null object reference
    at com.flipboard.bottomsheet.BottomSheetLayout.setSheetLayerTypeIfEnabled(BottomSheetLayout.java:468)
    at com.flipboard.bottomsheet.BottomSheetLayout.peekSheet(BottomSheetLayout.java:521)
```
I'm unsure if I'm supposed to call peekSheet() after dismissSheet(), but I can't find any documentation saying I shouldn't.

**Comment by hzsweers** [comment]
You'll need to call showWithSheetView again after dismissing before you can set any of the other states again. After dismissing, the child sheet is removed.

**Comment by hzsweers** [comment]
Not currently, no. You'd have to intercept touches yourself

**Comment by steffandroid** [comment]
Okay, thank you for the quick response!
